# Generated by Django 4.2.7 on 2024-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
