# Generated by Django 4.2.7 on 2024-05-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sessions_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="user",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
