# Generated by Django 4.2.7 on 2024-05-13 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sessions_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
