# Generated by Django 4.2.7 on 2024-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_sessions_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessions",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
