# Generated by Django 4.2.7 on 2024-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_classroom_teacher_alter_option_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name="test",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
