# Generated by Django 4.2.7 on 2024-02-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_classroom_content_type_classroom_picture_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="text",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="title",
            new_name="name",
        ),
    ]
