# Generated by Django 4.2.7 on 2024-03-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_text_option_name_rename_text_question_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="teacher",
            new_name="user",
        ),
    ]
