# Generated by Django 4.2.7 on 2024-03-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_teacher_school_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="user",
        ),
    ]
