# Generated by Django 4.2.7 on 2024-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_school_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="picture",
            new_name="classroom_picture",
        ),
        migrations.RenameField(
            model_name="option",
            old_name="picture",
            new_name="option_picture",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="picture",
            new_name="question_picture",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="picture",
            new_name="school_picture",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="picture",
            new_name="test_picture",
        ),
    ]
