# Generated by Django 4.2.7 on 2024-03-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_picture_classroom_classroom_picture_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="content_type",
            new_name="classroom_content_type",
        ),
        migrations.RenameField(
            model_name="option",
            old_name="content_type",
            new_name="option_content_type",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="content_type",
            new_name="question_content_type",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="content_type",
            new_name="school_content_type",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="content_type",
            new_name="test_content_type",
        ),
    ]
