# Generated by Django 4.2.7 on 2024-03-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_usertestsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestsubmission",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.option",
            ),
        ),
    ]
