# Generated by Django 4.2.7 on 2024-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_usertestsubmission_selected_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestsubmission",
            name="last_question_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
