# Generated by Django 4.2.7 on 2024-04-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_usertestsubmission_last_question_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_sound",
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_sound_content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
    ]
