# Generated by Django 4.2.7 on 2024-05-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_testrecord_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestRecord",
        ),
    ]
