# Generated by Django 4.2.7 on 2024-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_testrecords"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecords",
            name="total_recorded_score",
            field=models.FloatField(default=0),
        ),
    ]
