# Generated by Django 4.2.7 on 2024-05-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_testrecords_total_recorded_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecords",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.question",
            ),
        ),
    ]
