# Generated by Django 4.2.7 on 2024-05-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_testrecords_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertestsubmission",
            old_name="last_answered_question",
            new_name="question",
        ),
    ]
