# Generated by Django 4.2.7 on 2024-05-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_rename_last_answered_question_usertestsubmission_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestsubmission",
            name="group_id",
            field=models.IntegerField(default=0),
        ),
    ]
