# Generated by Django 4.2.7 on 2024-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_usertestsubmission_group_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertestsubmission",
            name="group_id",
        ),
        migrations.AddField(
            model_name="testrecords",
            name="group_id",
            field=models.IntegerField(default=0),
        ),
    ]
