# Generated by Django 4.2.7 on 2024-05-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sessions"),
        ("main", "0023_remove_usertestsubmission_group_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrecords",
            name="account_sessions",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.sessions",
            ),
        ),
    ]
