# Generated by Django 4.2.7 on 2024-05-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_sessions_number"),
        ("main", "0024_testrecords_account_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.sessions",
            ),
        ),
    ]
