# Generated by Django 4.2.7 on 2024-05-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_test_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="session",
        ),
    ]
