# Generated by Django 4.2.7 on 2024-05-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_test_classroom_test_classrooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="classrooms",
            new_name="classroom",
        ),
    ]
