# Generated by Django 4.2.7 on 2024-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_test_classroom_test_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="classroom",
        ),
        migrations.AddField(
            model_name="test",
            name="classroom",
            field=models.ManyToManyField(to="main.classroom"),
        ),
    ]
