# Generated by Django 4.2.7 on 2024-05-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_remove_test_classroom_test_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="classroom",
        ),
        migrations.AddField(
            model_name="test",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.classroom",
            ),
        ),
    ]
